apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
spec:
  gateways:
    - default/monitor-gateway # namespace/gateway
  hosts:
    - argocd.nemo.kaonmir.xyz
  http:
    - route:
        - destination:
            host: frontend.default.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kiali
spec:
  gateways:
    - default/monitor-gateway # namespace/gateway
  hosts:
    - kiali.nemo.kaonmir.xyz
  http:
    - route:
        - destination:
            host: kiali.monitoring.svc.cluster.local
            port:
              number: 20001
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
spec:
  gateways:
    - default/monitor-gateway # namespace/gateway
  hosts:
    - grafana.nemo.kaonmir.xyz
  http:
    - route:
        - destination:
            host: grafana.monitoring.svc.cluster.local
            port:
              number: 80
