apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/GoogleCloudPlatform/microservices-demo.git
    targetRevision: HEAD
    path: release
    # repoURL: <helm repo>
    # chart: argo
    # helm:
    #   valueFiles:
    #     - values-prod.yaml
  syncPolicy:
    automated: {}
    prune: true
