apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    # repoURL: https://github.com/GoogleCloudPlatform/microservices-demo.git
    # targetRevision: HEAD
    # path: release
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.46.0
    helm:
      values: |
        istio_namespace: istio-system
        deployment:
          node_selector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
        external_services:
          prometheus:
            url: http://prometheus-server.istio-system:80
  # syncPolicy:
  #   automated: {}
  #   prune: true
