# # https://operatorhub.io/operator/prometheus
# apiVersion: monitoring.coreos.com/v1
# kind: Prometheus
# metadata:
#   name: prometheus
#   namespace: observability
# spec:
#   replicas: 1
#   serviceAccountName: prometheus
#   serviceMonitorSelector:
#     matchLabels:
#       app: monitor
#   ruleSelector: {}
#   podMonitorSelector:
#     matchLabels:
#       app: monitor
#   probeSelector: {}
#   # enableAdminAPI: true
#   # alerting:
#   #   alertmanagers:
#   #     - namespace: monitoring
#   #       name: alertmanager-main
#   #       port: web
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus
#   namespace: observability
# spec:
#   type: ClusterIP
#   ports:
#     - name: web
#       port: 9090
#       protocol: TCP
#       targetPort: web
#   selector:
#     prometheus: prometheus
