apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: observability
spec:
  serviceAccount:
    skip: True
  ingress:
    enabled: True
  dataStorage:
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  deployment:
    securityContext:
      fsGroup: 472
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "root"
      admin_password: "secret"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
