alertmanager:
  nodeSelector:
    role: nodegroup_admin
  tolerations:
    - key: "TAINED_BY_ADMIN"
      operator: "Exists"
      effect: "NoSchedule"
  persistentVolume:
    storageClass: "gp2"
nodeExporter:
  tolerations:
    - key: "TAINED_BY_ADMIN"
      operator: "Exists"
      effect: "NoSchedule"
pushgateway:
  nodeSelector:
    role: nodegroup_admin
  tolerations:
    - key: "TAINED_BY_ADMIN"
      operator: "Exists"
      effect: "NoSchedule"
server:
  nodeSelector:
    role: nodegroup_admin
  tolerations:
    - key: "TAINED_BY_ADMIN"
      operator: "Exists"
      effect: "NoSchedule"
  persistentVolume:
    storageClass: "gp2"

  service:
    servicePort: 9090
