# https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: empty
  namespace: istio-system
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway-admin
        label:
          role: admin
        k8s:
          nodeSelector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
          hpaSpec:
            minReplicas: 1
            maxReplicas: 3
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:774026503161:certificate/0dd98ec7-efc6-42f5-9ae2-635e9e91654a
            # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
            # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"

      - enabled: true
        name: istio-ingressgateway-app
        label:
          role: app
        k8s:
          nodeSelector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
          # service:
          #   type: NodePort
          #   ports:
          #     - nodePort: 32398
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:774026503161:certificate/af201191-3f7c-4cdd-88c7-f7a679db88f7
            # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
            # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
          hpaSpec:
            minReplicas: 2
            maxReplicas: 6
    pilot: # = Istiod
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 4
        nodeSelector:
          role: nodegroup_admin
        tolerations:
          - key: "TAINED_BY_ADMIN"
            operator: "Exists"
            effect: "NoSchedule"
