apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nemo-smart
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: charts/nemo-smart
    repoURL: "https://github.com/kaonmir/nemo-helm-charts"
    targetRevision: HEAD
  project: default

  syncPolicy:
    automated: {}
