apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    # repoURL: https://github.com/GoogleCloudPlatform/microservices-demo.git
    # targetRevision: HEAD
    # path: release
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 15.5.3
    helm:
      values: |
        alertmanager:
          nodeSelector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
          persistentVolume:
            storageClass: "gp2"
        nodeExporter:
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
        pushgateway:
          nodeSelector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
        server:
          nodeSelector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
          persistentVolume:
            storageClass: "gp2"

  # syncPolicy:
  #   automated: {}
  #   prune: true
