apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-business
  namespace: default
spec:
  selector:
    role: business
  servers:
    - hosts:
        - "*.business.kaonmir.xyz"
        - "whereurl.com"
      port:
        name: http
        number: 80
        protocol: HTTP
    #   tls:
    #     httpsRedirect: false
    # - hosts:
    #     - "www.whereurl.com"
    #     - "whereurl.com"
    #     - test.business.kaonmir.xyz
    #   port:
    #     name: https
    #     number: 443
    #     protocol: HTTPS
    #   tls:
    #     mode: PASSTHROUGH
