# installCRDs: true
prometheus:
  enabled: false
nodeSelector:
  role: nodegroup_admin
tolerations:
  - key: "TAINED_BY_ADMIN"
    operator: "Exists"
    effect: "NoSchedule"
webhook:
  nodeSelector:
    role: nodegroup_admin
  tolerations:
    - key: "TAINED_BY_ADMIN"
      operator: "Exists"
      effect: "NoSchedule"
cainjector:
  nodeSelector:
    role: nodegroup_admin
  tolerations:
    - key: "TAINED_BY_ADMIN"
      operator: "Exists"
      effect: "NoSchedule"
startupapicheck:
  nodeSelector:
    role: nodegroup_admin
  tolerations:
    - key: "TAINED_BY_ADMIN"
      operator: "Exists"
      effect: "NoSchedule"
# syncPolicy:
