# https://www.jaegertracing.io/docs/1.32/operator/#production-strategy
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: istio-system
spec:
  selector:
    name: jaeger-operator
  strategy: production
  collector:
    #   maxReplicas: 5
  agent:
    strategy: DaemonSet
    tolerations:
      - key: "TAINED_BY_ADMIN"
        operator: "Exists"
        effect: "NoSchedule"
