# https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  namespace: istio-system
  components:
    base:
      enabled: true
      k8s:
        nodeSelector:
          role: nodegroup_admin
        tolerations:
          - key: "TAINED_BY_ADMIN"
            operator: "Exists"
            effect: "NoSchedule"
    ingressGateways:
      enabled: true
      # name:
      # namespace:
      k8s:
        nodeSelector:
          role: nodegroup_admin
        tolerations:
          - key: "TAINED_BY_ADMIN"
            operator: "Exists"
            effect: "NoSchedule"
    ingressGateways:
      enabled: false
