# https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: empty
  namespace: istio-system
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway-admin
        label:
          role: admin
        k8s:
          nodeSelector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
          hpaSpec:
            minReplicas: 1
            maxReplicas: 3
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            service.beta.kubernetes.io/aws-load-balancer-name: "isito-nlb-admin"

      - enabled: true
        name: istio-ingressgateway-business
        label:
          role: business
        k8s:
          nodeSelector:
            role: nodegroup_admin
          tolerations:
            - key: "TAINED_BY_ADMIN"
              operator: "Exists"
              effect: "NoSchedule"
          service:
            type: NodePort # ingress gateway 의 NodePort 사용
          hpaSpec:
            minReplicas: 1
            maxReplicas: 6
          serviceAnnotations:
            alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
            alb.ingress.kubernetes.io/healthcheck-port: "32727"
    pilot: # = Istiod
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 4
        nodeSelector:
          role: nodegroup_admin
        tolerations:
          - key: "TAINED_BY_ADMIN"
            operator: "Exists"
            effect: "NoSchedule"
